### PR TITLE
Stile for card information

### PR DESCRIPTION
**Pull request by MarcoAurelioAntonio**
### In this PR I did some style for the infomation cards.

image

### CODE REVIEW

**Review by biruk-bereka — CHANGES_REQUESTED** [review]
## STATUS: REQUIRED CHANGES ♻♻

Hello, @MarcoAurelioAntonio good job so far. But there are some issues you need to fix. See the comments below.

Screenshot (123)
Screenshot (124)

- You need to remove the extra space from the right.
- Make sure the cards are in the center of the page. 

If you have any question let me know.

**Comment by MarcoAurelioAntonio** [comment]
Hi @biruk-bereka !, Thanks!!....I fix the issue.

image

image


## I guess we need to work in the `Nav Bar` responsivnes:

image

**Review by NelsonAraujo93 — CHANGES_REQUESTED** [review]
#### Changes Required

Hello @MarcoAurelioAntonio , you did a great job but there is something that can enhance your UI, try to add a full width to the main container of this component

.reservation-container {
    overflow-y: scroll;
    height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    row-gap: 50px;
    widht:100%;   //hint   
}


Screenshot 2023-06-20 at 10 31 18 AM

**Comment by MarcoAurelioAntonio** [comment]
Hi @NelsonAraujo93 !, You rigth, i gorgot to do that... Is done now

**Pull request merged**
